### ISSUE TITLE
footer + message

### ISSUE THREAD

**Issue by benoitchocot** [WildCodeSchool/orleans-php-2003-project-loireetorleans#207]
toujours dans /gestion/profil, il n'y a pas de messages dans le tableau vide pour dire qu'il est vide.
Par ailleurs, dans ce même cas de situation, le footer se retrouve décalé comme dans une autre issue

(si ce n'est pas clair, mettez une donnée fausse dans la barre de recherche, vous verrez bien)

**Comment by JudgeBurger** [comment]
Done
